import{S as d,i}from"./assets/vendor-9310f15c.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const p=document.querySelector(".search-form"),l=new URL("https://pixabay.com/api/"),c=document.querySelector(".gallery"),u=document.querySelector(".loader"),y=new d(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});p.addEventListener("submit",s=>{s.preventDefault();const r={key:"41612762-752dc9341b43071862b7b3b8c",q:s.currentTarget.elements.query.value.trim(),image_type:"photo",orientation:"horizontal",safesearch:!0};l.search=new URLSearchParams(r),c.innerHTML="",u.style.display="block",fetch(l).then(o=>{if(!o.ok)throw new Error("Network response was not ok");return o.json()}).then(o=>{o.hits.length===0?i.error({title:"Error",position:"center",message:"Sorry, there are no images matching your search query. Please try again!"}):(c.innerHTML=f(o.hits),y.refresh())}).catch(o=>{i.error({title:"Error",position:"center",message:"Sorry, there are no images matching your search query. Please try again later!"})}).finally(()=>{u.style.display="none"})});function f(s){return s.reduce((n,r)=>n+`<li class="img-gallery-item"><a class="gallery-link" href="${r.largeImageURL}"><img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" width="${r.webformatWidth}"></a>
        <div class="info-img">
          <p>Likes<span>${r.likes}</span></p>
          <p>Views<span>${r.views}</span></p>
          <p>Comments<span>${r.comments}</span></p>
          <p>Downloads<span>${r.downloads}</span></p>
        </div>
      </li>`,"")}
//# sourceMappingURL=commonHelpers.js.map
